import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';

export const routes: Routes = [
  // Login pages
  { path: 'login-staff', loadComponent: () => import('./pages/login-staff/login-staff').then(c => c.LoginStaff) },
  { path: 'login-admin', loadComponent: () => import('./pages/login-admin/login-admin').then(c => c.LoginAdmin) },
  { path: 'login-director', loadComponent: () => import('./pages/login-admin/login-admin').then(c => c.LoginAdmin) },
  { path: 'login-guardian', loadComponent: () => import('./pages/login-guardian/login-guardian').then(c => c.LoginGuardian) },

  // Dashboard / Feature pages
  { path: 'admin', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/admin-dashboard/admin-dashboard').then(c => c.AdminDashboard) },
  { path: 'student', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/student-dashboard/student-dashboard').then(c => c.StudentDashboard) },
  { path: 'teacher', canActivate: [authGuard], data: { roles: ['teacher'] }, loadComponent: () => import('./features/teacher-dashboard/teacher-dashboard').then(c => c.TeacherDashboard) },
  { path: 'parent', canActivate: [authGuard], data: { roles: ['parent'] }, loadComponent: () => import('./features/parent-dashboard/parent-dashboard').then(c => c.ParentDashboard) },
  { path: 'profile', canActivate: [authGuard], loadComponent: () => import('./features/profile/profile').then(c => c.Profile) },
  { path: 'class-analysis', canActivate: [authGuard], loadComponent: () => import('./features/class-analysis/class-analysis').then(c => c.ClassAnalysis) },
  { path: 'admin-schedule', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/admin-schedule/admin-schedule').then(c => c.AdminSchedule) },
  { path: 'class-schedule', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/class-schedule/class-schedule').then(c => c.ClassSchedule) },
  { path: 'teacher-schedule', canActivate: [authGuard], data: { roles: ['teacher'] }, loadComponent: () => import('./features/teacher-schedule/teacher-schedule').then(c => c.TeacherSchedule) },
  { path: 'assignment-management', canActivate: [authGuard], loadComponent: () => import('./features/assignment-management/assignment-management').then(c => c.AssignmentManagement) },
  { path: 'assignment-submissions/:id', canActivate: [authGuard], loadComponent: () => import('./features/assignment-submissions/assignment-submissions').then(c => c.AssignmentSubmissions) },
  { path: 'homework', canActivate: [authGuard], loadComponent: () => import('./features/homework/homework').then(c => c.Homework) },
  { path: 'student-assignments/:assignmentId/take', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/homework/homework').then(c => c.Homework) },
  { path: 'student-assignments/submissions/:submissionId', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/assignment-submission-result/assignment-submission-result').then(c => c.AssignmentSubmissionResult) },
  { path: 'my-assignments', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/my-assignments/my-assignments').then(c => c.MyAssignments) },
  { path: 'my-exams', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/my-exams/my-exams').then(c => c.MyExams) },
  { path: 'student-exams/:examId/take/:attemptId', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/take-exam/take-exam').then(c => c.TakeExam) },
  { path: 'student-exams/results/:attemptId', canActivate: [authGuard], data: { roles: ['student'] }, loadComponent: () => import('./features/exam-result/exam-result').then(c => c.ExamResult) },
  { path: 'exam-management', canActivate: [authGuard], loadComponent: () => import('./features/exam-management/exam-management').then(c => c.ExamManagement) },
  { path: 'exam-generator', canActivate: [authGuard], loadComponent: () => import('./features/exam-generator/exam-generator').then(c => c.ExamGenerator) },
  { path: 'question-bank', canActivate: [authGuard], data: { roles: ['admin', 'teacher'] }, loadComponent: () => import('./features/question-bank/question-bank').then(c => c.QuestionBank) },
  { path: 'monthly-report', canActivate: [authGuard], loadComponent: () => import('./features/monthly-report/monthly-report').then(c => c.MonthlyReport) },
  { path: 'study-planner', canActivate: [authGuard], loadComponent: () => import('./features/study-planner/study-planner').then(c => c.StudyPlanner) },
  { path: 'chat', canActivate: [authGuard], loadComponent: () => import('./features/chat/chat').then(c => c.Chat) },
  { path: 'chat-ai', canActivate: [authGuard], loadComponent: () => import('./features/chat-ai/chat-ai').then(c => c.ChatAi) },
  { path: 'notifications', canActivate: [authGuard], loadComponent: () => import('./features/notifications/notifications').then(c => c.Notifications) },
  { path: 'digital-library', canActivate: [authGuard], loadComponent: () => import('./features/digital-library/digital-library').then(c => c.DigitalLibrary) },
  { path: 'reports', canActivate: [authGuard], data: { roles: ['parent'] }, loadComponent: () => import('./features/reports/reports').then(c => c.Reports) },
  { path: 'reports-academic', canActivate: [authGuard], loadComponent: () => import('./features/reports-academic/reports-academic').then(c => c.ReportsAcademic) },
  { path: 'reports-training', canActivate: [authGuard], loadComponent: () => import('./features/reports-training/reports-training').then(c => c.ReportsTraining) },
  { path: 'analysis', canActivate: [authGuard], loadComponent: () => import('./features/analysis-ai/analysis-ai').then(c => c.AnalysisAi) },
  { path: 'announcements', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/announcements/announcements').then(c => c.Announcements) },
  { path: 'admin-meetings', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/admin-meetings/admin-meetings').then(c => c.AdminMeetings) },
  { path: 'import-students', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/import-students/import-students').then(c => c.ImportStudents) },
  { path: 'account-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/user-management/user-management').then(c => c.UserManagement) },
  { path: 'user-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/user-management/user-management').then(c => c.UserManagement) },
  { path: 'teacher-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/add-teacher/add-teacher').then(c => c.AddTeacher) },
  { path: 'add-teacher', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/add-teacher/add-teacher').then(c => c.AddTeacher) },
  { path: 'student-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/student-management/student-management').then(c => c.StudentManagement) },
  { path: 'transfer-student', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/transfer-student/transfer-student').then(c => c.TransferStudent) },
  { path: 'student-progression', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/student-progression/student-progression').then(c => c.StudentProgression) },
  { path: 'settings', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/settings/settings').then(c => c.Settings) },
  { path: 'grade-monitor', canActivate: [authGuard], loadComponent: () => import('./features/grade-monitor/grade-monitor').then(c => c.GradeMonitor) },
  { path: 'child-progress', canActivate: [authGuard], loadComponent: () => import('./features/child-progress/child-progress').then(c => c.ChildProgress) },
  { path: 'parent-meeting-request', canActivate: [authGuard], data: { roles: ['parent'] }, loadComponent: () => import('./features/parent-meeting-request/parent-meeting-request').then(c => c.ParentMeetingRequest) },
  { path: 'parent-schedule', canActivate: [authGuard], data: { roles: ['parent'] }, loadComponent: () => import('./features/parent-schedule/parent-schedule').then(c => c.ParentSchedule) },
  { path: 'teacher-assignments', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/teacher-assignments/teacher-assignments').then(c => c.TeacherAssignments) },
  { path: 'room-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/room-management/room-management').then(c => c.RoomManagement) },
  { path: 'class-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/class-management/class-management').then(c => c.ClassManagement) },
  { path: 'subject-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/subject-management/subject-management').then(c => c.SubjectManagement) },
  { path: 'lesson-feedback', canActivate: [authGuard], data: { roles: ['admin', 'teacher', 'student'] }, loadComponent: () => import('./features/lesson-feedback/lesson-feedback').then(c => c.LessonFeedback) },
  { path: 'certificate-management', canActivate: [authGuard], data: { roles: ['admin'] }, loadComponent: () => import('./features/certificate-management/certificate-management').then(c => c.CertificateManagement) },
  { path: 'book-parser', canActivate: [authGuard], data: { roles: ['admin', 'teacher'] }, loadComponent: () => import('./features/book-parser/book-parser').then(c => c.BookParser) },
  { path: 'historical-data', canActivate: [authGuard], data: { roles: ['admin', 'teacher', 'student', 'parent'] }, loadComponent: () => import('./features/historical-data/historical-data').then(c => c.HistoricalDataComponent) },
  { path: 'index', loadComponent: () => import('./features/landing/landing').then(c => c.Landing) },

  // Default redirect
  { path: '', redirectTo: '/index', pathMatch: 'full' },
  { path: '**', redirectTo: '/index' },
];
